#!/bin/bash
# Usage: script/regenerate
#

set -e

case "$1" in
-h | --help )
  sed -ne '/^#/!q;s/.\{1,2\}//;1d;p' < "$0"
  exit 0
  ;;
esac

bundle exec rake db:dump > db/emoji2.json
mv db/emoji2.json db/emoji.json

if git diff --exit-code --stat -- db/emoji.json; then
  echo "Done. The file \`db/emoji.json\` remains unchanged."
fi
