name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        ruby: ["2.7", "3.0", "3.1"]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}
        bundler-cache: true
    
    - name: Run tests
      run: bundle exec rake
